openapi: 3.0.0
info:
  title: "API_ResidentService"
  description: "API Services"
  version: "20250225135911"
servers:
  - url: https://staging.comforta.yukon.software/api
paths:
components:
  securitySchemes:
    oAuthGXGAM:
      type: oauth2
      description: GAM OAuth 2
      flows:
        password:          
          tokenUrl: https://staging.comforta.yukon.software/oauth/gam/v2.0/access_token
          scopes: 
            fullcontrol: Full access

  schemas:
  
 
