gx.setStaticDirectory(gx.text.chr(47));
gx.setBlankWhenEmptyDate( false );

gx.gxBuild =  1918140 ;
gx.gen.net = true;
gx.datepickerImage='Resources/calendar.png';
gx.grid.deleteImage='Resources/DeleteRow.gif';
gx.grid.undeleteImage='Resources/UndeleteRow.gif';
gx.blankImage="blank.jpg";
gx.ascImage="asc.gif";
gx.descImage="desc.gif";
gx.expandImage="expand.gif";
gx.collapseImage="collapse.gif";
gx.downloadImage="download.gif";
gx.indicatorImage="indicator.gif";
gx.promptImage='Resources/prompt.png';
gx.myLocationImage="locateMe.gif";
gx.resizeImage="resize.gif";
gx.csv.stopOnError = false;
gx.csv.dismissSeconds = 0;
gx.csv.messagePosition =  "bottom" ;
gx.csv.overlap = false;
gx.csv.oneAtAtime = false;
gx.HTML5 = true;
